base_output_dir = '../attn-test-output/'
base_serialized_models_dir = 'models/'
base_data_dir = '../data/'
dir_with_config_files = 'configs/'
images_dir = 'imgs/'
tex_files_dir = 'generated_tex_files/'
